services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "3001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongo:
