FROM node:24-bookworm-slim AS build

WORKDIR /app
RUN npm install --global pnpm@12.9.1

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY packages/schemas/package.json packages/schemas/package.json
RUN pnpm install --frozen-lockfile

COPY apps/frontend apps/frontend
COPY packages/schemas packages/schemas
RUN pnpm --filter frontend build

FROM caddy:2.10.2

EXPOSE 3000

COPY apps/frontend/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/apps/frontend/dist /srv
