FROM node:24-bookworm-slim AS dependencies

WORKDIR /app
RUN npm install --global pnpm@12.9.1

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/frontend/package.json apps/frontend/package.json
COPY packages/schemas/package.json packages/schemas/package.json
RUN pnpm install --frozen-lockfile --prod

FROM node:24-bookworm-slim

WORKDIR /app
ENV NODE_ENV=production

COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/apps/backend/node_modules ./apps/backend/node_modules
COPY apps/backend/package.json apps/backend/package.json
COPY apps/backend/src apps/backend/src
COPY packages/schemas packages/schemas

EXPOSE 3000
CMD ["node", "apps/backend/src/server.js"]
